### ISSUE TITLE
Update librespot to v.0.4.2

### ISSUE THREAD

**Issue by fightforlife** [dubo-dubon-duponey/docker-spotify#14]
Would it be possible to  update the librespot binary to 0.4.2 in this Docker image.
Currently playback fails, see:
https://github.com/librespot-org/librespot/releases/tag/v0.4.2

**Comment by dubo-dubon-duponey** [comment]
Will do soon.
Ping me here if you do not hear back before end of week.

**Comment by dubo-dubon-duponey** [comment]
Just published with librespot v0.4.2

https://hub.docker.com/r/dubodubonduponey/spotify/tags

I do not have time to test this rn - if you want to give it a spin and lmk if there is any issue here, that would be nice.

**Comment by fightforlife** [comment]
Thank you very much for the quick update!
Playback is working again as it should.

I noticed a small issue: In the new build the mDNS Display name is not set correctly. I am using the NAME eenv variable as before.
![image](https://user-images.githubusercontent.com/5511687/182210586-13af2239-2010-47a1-a0e7-772af888e687.png)

**Comment by dubo-dubon-duponey** [comment]
Readme is probably out of wack.

You should use `MDNS_NAME` env variable now.
