### ISSUE TITLE
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

### ISSUE THREAD

**Issue by GAZ082** [dubo-dubon-duponey/docker-spotify#17]
Tried to run your example and got that error.

I'm using a cubox which is an armv7 arch.

Thanks!

**Comment by dubo-dubon-duponey** [comment]
Hey.

I stopped building for arm/v7 some time ago (slow build, no interest on my side).
Did not realize some people were still using it...

Rebuilding now with arm/v7.
Stay tuned.

**Comment by GAZ082** [comment]
Hey bud. Thanks for the effort! I just went ahead and compiled librespot for my Cubox-I.

You can close this if you want!

**Comment by dubo-dubon-duponey** [comment]
That is fair!
Glad you found a way!

Yep, looks like I did rip off my armv7 toolchain - I will update the README to make it clearer I am no longer supporting armv7.

Sorry for the trouble and the old README :)
